Добавляет каталог
htmlacademy-htmlcss/1375337-sedona-32 pull request #3
Opened 2021-09-28 18:56 UTC by LomaevaVV

Плюс исправления главной страницы сайта

2021-09-29 15:08 UTC, tinakuzmenko requested changes
В этот раз немного больше замечаний, потому давай немного доработаем и потом уже я приму.

2021-09-29 15:08 UTC, tinakuzmenko commented on catalog.html
> +        <ul class="hotel-list">
А вот тут я бы не стала делать списком, потому что список должен быть неразрывным, да и в принципе он менее удобен и сильно связывает руки. Представь, что клиент захотел посреди списка влепить какой-нибудь баннер с акцией? И что ты будешь делать? Разобьешь товары на два списка? Не очень-то удобно. Так что давай мы все карточки просто сделаем в `div`. Так будет проще.

2021-09-29 15:08 UTC, tinakuzmenko commented on catalog.html
> +              <img
Давай картинку отдельно вынесем от заголовка, потому что будет сложно стилизовать. Да и не нужна она в этой ссылке.

2021-09-29 15:08 UTC, tinakuzmenko commented on catalog.html
> +            <label class="hotel-to-favorite visually-hidden">
Тут не нужен инпут (к тому же, без формы инпуты на курсе использовать нельзя), просто сделай кнопку "В избранное".

2021-09-29 15:08 UTC, tinakuzmenko commented on catalog.html
> +        <label for="hotels-on-page">Гостиниц на странице:</label>
Нужно обернуть селект в форму.

2021-09-29 19:46 UTC, LomaevaVV commented on index.html
> +        <h1 class="advantages-title">
Когда Выделяла секцию приветствия сама про это подумала, что надо так сделать. Хотела с тобой посоветоваться, да отвлеклась и забыла)))

2021-09-29 19:56 UTC, LomaevaVV commented on catalog.html
> +      <header class="inner-header">
на лекции советовали подобную менюшку сделать вторым хеддером. Акцентировали, что вот пример когда может быть два хеддера. Типа такая менюшка может повторяться на каждой  не главной странице. 

https://up.htmlacademy.ru/htmlcss/32/demos/5943#30

Исправлять?

2021-09-29 19:58 UTC, LomaevaVV commented on catalog.html
> +      <section class="catalog-hotels">
Давай сделаю так)

2021-09-30 08:45 UTC, LomaevaVV commented on catalog.html
> +                  <span class="control-mark"></span>
Оставила пока   <span class="control-mark"></span>. После лекции по css и на этапе формирования стилей решу, пока не понимаю даже  толком как мне хочется и как лучше).

2021-09-30 08:48 UTC, LomaevaVV commented on catalog.html
> +          <button class="visually-hidden" type="submit">
ок
Просто по селекту выполняется действие?

2021-09-30 15:28 UTC, merged

2021-10-01 17:05 UTC, LomaevaVV commented on catalog.html
>              <p>
туплю наверное, но не могу понять( Что именно удалить забыла?